### ISSUE TITLE
GY521_standalone_app example problems

### ISSUE THREAD

**Issue by untitledlt** [rondawg369/esp8266-sensor-mpu6050#1]
Looks like we're missing few files here like `MPU6050.h` and `WiFiConfig.h`.

**Comment by FordMustang0288** [comment]
Any word on this @rondawg369

**Comment by rondawg369** [comment]
Apologies, I had started my own MPU6050 library, and then found this one, which I believe should work:

https://github.com/jrowberg/i2cdevlib
by Jeff Rowberg

The WiFiConfig.h is just the wifi configuration.  I'll upload an example one.

**Comment by rondawg369** [comment]
The WiFiConfig.h was explained in my blog post here: https://olivertechnologydevelopment.wordpress.com/2017/08/29/esp8266-sensor-series-gy-521-imu-part-3/
